import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { mealplanApi } from '../api/mealplan.api'
import { MealPlanCard } from '../components/ai/MealPlanCard'
import { Button } from '../components/ui/Button'
import { Input } from '../components/ui/Input'
import { PageSpinner } from '../components/ui/Spinner'
import { useGenerateMealPlan } from '../hooks/useAI'
import type { MealPlan } from '../types/mealplan.types'
import toast from 'react-hot-toast'

export function MealPlanner() {
  const qc = useQueryClient()
  const [goal, setGoal]             = useState('')
  const [calories, setCalories]     = useState('2000')
  const [restrictions, setRestrictions] = useState('')
  const [activePlan, setActivePlan] = useState<MealPlan | null>(null)

  const { data: plans = [], isLoading } = useQuery({
    queryKey: ['mealplans'],
    queryFn: () => mealplanApi.getAll().then((r) => r.data.data?.plans ?? []),
  })

  const generateMutation = useGenerateMealPlan()

  const handleGenerate = async () => {
    if (!goal) return toast.error('Please enter a goal')
    const plan = await generateMutation.mutateAsync({
      goal,
      calorieTarget: Number(calories),
      restrictions: restrictions.split(',').map((s) => s.trim()).filter(Boolean),
    })
    if (plan) {
      setActivePlan(plan)
      qc.invalidateQueries({ queryKey: ['mealplans'] })
    }
  }

  if (isLoading) return <PageSpinner />

  return (
    <main className="mx-auto max-w-7xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">AI Meal Planner</h1>
        <p className="text-gray-500 mt-1">Get a personalised 7-day meal plan generated by AI.</p>
      </div>

      <div className="rounded-2xl bg-white border shadow-sm p-6 space-y-4">
        <h2 className="font-semibold text-gray-800">Generate New Plan</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <Input label="Your goal" placeholder="e.g. weight loss, muscle gain" value={goal} onChange={(e) => setGoal(e.target.value)} />
          <Input label="Daily calories" type="number" value={calories} onChange={(e) => setCalories(e.target.value)} />
          <Input label="Restrictions (comma-separated)" placeholder="e.g. gluten-free, vegan" value={restrictions} onChange={(e) => setRestrictions(e.target.value)} />
        </div>
        <Button isLoading={generateMutation.isPending} onClick={handleGenerate}>
          ✨ Generate AI Meal Plan
        </Button>
      </div>

      {activePlan && (
        <div>
          <h2 className="font-semibold text-gray-900 mb-4">📅 {activePlan.title}</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {activePlan.days.map((day) => <MealPlanCard key={day.dayName} day={day} />)}
          </div>
        </div>
      )}

      {plans.length > 0 && (
        <div>
          <h2 className="font-semibold text-gray-900 mb-4">Your Saved Plans</h2>
          <div className="space-y-6">
            {plans.map((plan) => (
              <div key={plan._id}>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-medium text-gray-800">{plan.title}</h3>
                  <button
                    onClick={() => mealplanApi.delete(plan._id).then(() => qc.invalidateQueries({ queryKey: ['mealplans'] }))}
                    className="text-xs text-red-400 hover:text-red-600"
                  >
                    Delete
                  </button>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                  {plan.days.map((day) => <MealPlanCard key={day.dayName} day={day} />)}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </main>
  )
}
